# Generated by Django 2.1.15 on 2020-08-02 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('max_volume', models.IntegerField()),
                ('field', models.FloatField()),
                ('imgurl', models.URLField()),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firms_stuff', to='accounts.Firm')),
                ('rewards', models.ManyToManyField(related_name='rewards_stuff', to='rewards.Reward')),
            ],
        ),
    ]
